version: 2
jobs:
  build:
    working_directory: ~/akbash
    docker:
      - image: circleci/python:3.6.4
        environment:
          AKBASH_CONFIG_FILE: akbash_circle_settings.ini
    steps:
      - checkout
      - run:
          name: Set environment variables for cache keys
          command: |
            # MONTH used to expire keys once per month since were not using
            #   specific pip package versions in requirements.txt
            MONTH=`date +%Y-%m`
            PYTHON_VER=`python3 --version`
            echo 'export MONTH="$MONTH"' >> $BASH_ENV
            echo 'export PYTHON_VER="$PYTHON_VER"' >> $BASH_ENV
      - run:
          name: Install unixodbc-dev
          command: |
            sudo apt-get update
            sudo apt-get install unixodbc-dev
      - restore_cache:
          # Incriment the "r" number if you need to rebuild the cache.
          key: pip-r1-{{ .Environment.PYTHON_VER }}-{{ .Environment.MONTH }}-{{ checksum "requirements.txt" }}
      - run:
          name: Create Virtualenv and Install Requirements
          command: |
            virtualenv -p python3 virtualenv
            source virtualenv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: pip-r1-{{ .Environment.PYTHON_VER }}-{{ .Environment.MONTH }}-{{ checksum "requirements.txt" }}
          paths:
            - "virtualenv"
      - run:
          name: Make Migrations
          command: |
            source virtualenv/bin/activate
            python manage.py makemigrations
            python manage.py migrate
      - run:
          name: Run Tests
          command: |
            source virtualenv/bin/activate
            python manage.py test
      # No need to store results or artifacts.
      # - store_test_results:
      #     path: test-results/
      # - store_artifacts:
      #     path: test-results/
      #     destination: tr1
